/**
 * PointTheMap - World Countries Database
 * ======================================
 * 177 countries for Country mode
 *
 * Structure:
 * - name: Country name (English)
 * - countryId: ISO 3166-1 alpha-3 code
 * - popular: true = major/well-known country (52 countries)
 *            false = less known country (125 countries)
 *
 * Source: Natural Earth Data (110m resolution)
 *
 * @typedef {{ name: string, countryId: string, popular: boolean }} CountryEntry
 */

export const countries = [
  { name: "Argentina", countryId: "ARG", popular: true },
  { name: "Australia", countryId: "AUS", popular: true },
  { name: "Austria", countryId: "AUT", popular: true },
  { name: "Bangladesh", countryId: "BGD", popular: true },
  { name: "Belgium", countryId: "BEL", popular: true },
  { name: "Brazil", countryId: "BRA", popular: true },
  { name: "Canada", countryId: "CAN", popular: true },
  { name: "Chile", countryId: "CHL", popular: true },
  { name: "China", countryId: "CHN", popular: true },
  { name: "Colombia", countryId: "COL", popular: true },
  { name: "Czechia", countryId: "CZE", popular: true },
  { name: "Denmark", countryId: "DNK", popular: true },
  { name: "Egypt", countryId: "EGY", popular: true },
  { name: "Finland", countryId: "FIN", popular: true },
  { name: "France", countryId: "-99", popular: true },
  { name: "Germany", countryId: "DEU", popular: true },
  { name: "Greece", countryId: "GRC", popular: true },
  { name: "India", countryId: "IND", popular: true },
  { name: "Indonesia", countryId: "IDN", popular: true },
  { name: "Iran", countryId: "IRN", popular: true },
  { name: "Ireland", countryId: "IRL", popular: true },
  { name: "Israel", countryId: "ISR", popular: true },
  { name: "Italy", countryId: "ITA", popular: true },
  { name: "Japan", countryId: "JPN", popular: true },
  { name: "Malaysia", countryId: "MYS", popular: true },
  { name: "Mexico", countryId: "MEX", popular: true },
  { name: "Morocco", countryId: "MAR", popular: true },
  { name: "Netherlands", countryId: "NLD", popular: true },
  { name: "New Zealand", countryId: "NZL", popular: true },
  { name: "Nigeria", countryId: "NGA", popular: true },
  { name: "Norway", countryId: "-99", popular: true },
  { name: "Pakistan", countryId: "PAK", popular: true },
  { name: "Peru", countryId: "PER", popular: true },
  { name: "Philippines", countryId: "PHL", popular: true },
  { name: "Poland", countryId: "POL", popular: true },
  { name: "Portugal", countryId: "PRT", popular: true },
  { name: "Romania", countryId: "ROU", popular: true },
  { name: "Russia", countryId: "RUS", popular: true },
  { name: "Saudi Arabia", countryId: "SAU", popular: true },
  { name: "South Africa", countryId: "ZAF", popular: true },
  { name: "South Korea", countryId: "KOR", popular: true },
  { name: "Spain", countryId: "ESP", popular: true },
  { name: "Sweden", countryId: "SWE", popular: true },
  { name: "Switzerland", countryId: "CHE", popular: true },
  { name: "Thailand", countryId: "THA", popular: true },
  { name: "Turkey", countryId: "TUR", popular: true },
  { name: "Ukraine", countryId: "UKR", popular: true },
  { name: "United Arab Emirates", countryId: "ARE", popular: true },
  { name: "United Kingdom", countryId: "GBR", popular: true },
  { name: "United States of America", countryId: "USA", popular: true },
  { name: "Venezuela", countryId: "VEN", popular: true },
  { name: "Vietnam", countryId: "VNM", popular: true },
  { name: "Afghanistan", countryId: "AFG", popular: false },
  { name: "Albania", countryId: "ALB", popular: false },
  { name: "Algeria", countryId: "DZA", popular: false },
  { name: "Angola", countryId: "AGO", popular: false },
  { name: "Antarctica", countryId: "ATA", popular: false },
  { name: "Armenia", countryId: "ARM", popular: false },
  { name: "Azerbaijan", countryId: "AZE", popular: false },
  { name: "Bahamas", countryId: "BHS", popular: false },
  { name: "Belarus", countryId: "BLR", popular: false },
  { name: "Belize", countryId: "BLZ", popular: false },
  { name: "Benin", countryId: "BEN", popular: false },
  { name: "Bhutan", countryId: "BTN", popular: false },
  { name: "Bolivia", countryId: "BOL", popular: false },
  { name: "Bosnia and Herz.", countryId: "BIH", popular: false },
  { name: "Botswana", countryId: "BWA", popular: false },
  { name: "Brunei", countryId: "BRN", popular: false },
  { name: "Bulgaria", countryId: "BGR", popular: false },
  { name: "Burkina Faso", countryId: "BFA", popular: false },
  { name: "Burundi", countryId: "BDI", popular: false },
  { name: "Cambodia", countryId: "KHM", popular: false },
  { name: "Cameroon", countryId: "CMR", popular: false },
  { name: "Central African Rep.", countryId: "CAF", popular: false },
  { name: "Chad", countryId: "TCD", popular: false },
  { name: "Congo", countryId: "COG", popular: false },
  { name: "Costa Rica", countryId: "CRI", popular: false },
  { name: "Côte d'Ivoire", countryId: "CIV", popular: false },
  { name: "Croatia", countryId: "HRV", popular: false },
  { name: "Cuba", countryId: "CUB", popular: false },
  { name: "Cyprus", countryId: "CYP", popular: false },
  { name: "Dem. Rep. Congo", countryId: "COD", popular: false },
  { name: "Djibouti", countryId: "DJI", popular: false },
  { name: "Dominican Rep.", countryId: "DOM", popular: false },
  { name: "Ecuador", countryId: "ECU", popular: false },
  { name: "El Salvador", countryId: "SLV", popular: false },
  { name: "Eq. Guinea", countryId: "GNQ", popular: false },
  { name: "Eritrea", countryId: "ERI", popular: false },
  { name: "Estonia", countryId: "EST", popular: false },
  { name: "eSwatini", countryId: "SWZ", popular: false },
  { name: "Ethiopia", countryId: "ETH", popular: false },
  { name: "Falkland Is.", countryId: "FLK", popular: false },
  { name: "Fiji", countryId: "FJI", popular: false },
  { name: "Fr. S. Antarctic Lands", countryId: "ATF", popular: false },
  { name: "Gabon", countryId: "GAB", popular: false },
  { name: "Gambia", countryId: "GMB", popular: false },
  { name: "Georgia", countryId: "GEO", popular: false },
  { name: "Ghana", countryId: "GHA", popular: false },
  { name: "Greenland", countryId: "GRL", popular: false },
  { name: "Guatemala", countryId: "GTM", popular: false },
  { name: "Guinea", countryId: "GIN", popular: false },
  { name: "Guinea-Bissau", countryId: "GNB", popular: false },
  { name: "Guyana", countryId: "GUY", popular: false },
  { name: "Haiti", countryId: "HTI", popular: false },
  { name: "Honduras", countryId: "HND", popular: false },
  { name: "Hungary", countryId: "HUN", popular: false },
  { name: "Iceland", countryId: "ISL", popular: false },
  { name: "Iraq", countryId: "IRQ", popular: false },
  { name: "Jamaica", countryId: "JAM", popular: false },
  { name: "Jordan", countryId: "JOR", popular: false },
  { name: "Kazakhstan", countryId: "KAZ", popular: false },
  { name: "Kenya", countryId: "KEN", popular: false },
  { name: "Kosovo", countryId: "-99", popular: false },
  { name: "Kuwait", countryId: "KWT", popular: false },
  { name: "Kyrgyzstan", countryId: "KGZ", popular: false },
  { name: "Laos", countryId: "LAO", popular: false },
  { name: "Latvia", countryId: "LVA", popular: false },
  { name: "Lebanon", countryId: "LBN", popular: false },
  { name: "Lesotho", countryId: "LSO", popular: false },
  { name: "Liberia", countryId: "LBR", popular: false },
  { name: "Libya", countryId: "LBY", popular: false },
  { name: "Lithuania", countryId: "LTU", popular: false },
  { name: "Luxembourg", countryId: "LUX", popular: false },
  { name: "Madagascar", countryId: "MDG", popular: false },
  { name: "Malawi", countryId: "MWI", popular: false },
  { name: "Mali", countryId: "MLI", popular: false },
  { name: "Mauritania", countryId: "MRT", popular: false },
  { name: "Moldova", countryId: "MDA", popular: false },
  { name: "Mongolia", countryId: "MNG", popular: false },
  { name: "Montenegro", countryId: "MNE", popular: false },
  { name: "Mozambique", countryId: "MOZ", popular: false },
  { name: "Myanmar", countryId: "MMR", popular: false },
  { name: "N. Cyprus", countryId: "-99", popular: false },
  { name: "Namibia", countryId: "NAM", popular: false },
  { name: "Nepal", countryId: "NPL", popular: false },
  { name: "New Caledonia", countryId: "NCL", popular: false },
  { name: "Nicaragua", countryId: "NIC", popular: false },
  { name: "Niger", countryId: "NER", popular: false },
  { name: "North Korea", countryId: "PRK", popular: false },
  { name: "North Macedonia", countryId: "MKD", popular: false },
  { name: "Oman", countryId: "OMN", popular: false },
  { name: "Palestine", countryId: "PSE", popular: false },
  { name: "Panama", countryId: "PAN", popular: false },
  { name: "Papua New Guinea", countryId: "PNG", popular: false },
  { name: "Paraguay", countryId: "PRY", popular: false },
  { name: "Puerto Rico", countryId: "PRI", popular: false },
  { name: "Qatar", countryId: "QAT", popular: false },
  { name: "Rwanda", countryId: "RWA", popular: false },
  { name: "S. Sudan", countryId: "SSD", popular: false },
  { name: "Senegal", countryId: "SEN", popular: false },
  { name: "Serbia", countryId: "SRB", popular: false },
  { name: "Sierra Leone", countryId: "SLE", popular: false },
  { name: "Slovakia", countryId: "SVK", popular: false },
  { name: "Slovenia", countryId: "SVN", popular: false },
  { name: "Solomon Is.", countryId: "SLB", popular: false },
  { name: "Somalia", countryId: "SOM", popular: false },
  { name: "Somaliland", countryId: "-99", popular: false },
  { name: "Sri Lanka", countryId: "LKA", popular: false },
  { name: "Sudan", countryId: "SDN", popular: false },
  { name: "Suriname", countryId: "SUR", popular: false },
  { name: "Syria", countryId: "SYR", popular: false },
  { name: "Taiwan", countryId: "TWN", popular: false },
  { name: "Tajikistan", countryId: "TJK", popular: false },
  { name: "Tanzania", countryId: "TZA", popular: false },
  { name: "Timor-Leste", countryId: "TLS", popular: false },
  { name: "Togo", countryId: "TGO", popular: false },
  { name: "Trinidad and Tobago", countryId: "TTO", popular: false },
  { name: "Tunisia", countryId: "TUN", popular: false },
  { name: "Turkmenistan", countryId: "TKM", popular: false },
  { name: "Uganda", countryId: "UGA", popular: false },
  { name: "Uruguay", countryId: "URY", popular: false },
  { name: "Uzbekistan", countryId: "UZB", popular: false },
  { name: "Vanuatu", countryId: "VUT", popular: false },
  { name: "W. Sahara", countryId: "ESH", popular: false },
  { name: "Yemen", countryId: "YEM", popular: false },
  { name: "Zambia", countryId: "ZMB", popular: false },
  { name: "Zimbabwe", countryId: "ZWE", popular: false }
];

/**
 * Get country by ID
 * @param {string} countryId - ISO 3166-1 alpha-3 code
 * @returns {CountryEntry|undefined}
 */
export function getCountryById(countryId) {
  return countries.find(c => c.countryId === countryId);
}

/**
 * Get country by name
 * @param {string} name - Country name
 * @returns {CountryEntry|undefined}
 */
export function getCountryByName(name) {
  return countries.find(c => c.name === name);
}
