name: Deploy to itch.io
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4

    # 1. On utilise l'action recommandée pour installer Butler proprement
    - name: Setup Butler
      uses: remarkablegames/setup-butler@v2
      with:
        # Cette action va chercher la dernière version stable automatiquement
        version: latest

    # 2. On lance la commande push standard
    - name: Push to itch.io
      env:
        BUTLER_API_KEY: ${{ secrets.BUTLER_CREDENTIALS }}
      run: |
        # La commande est simple : butler push <dossier> <user>/<jeu>:<canal>
        butler push . vandanael/point-the-map:web --userversion-file VERSION || butler push . vandanael/point-the-map:web