name: Deploy to itch.io
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install and Run Butler
      env:
        BUTLER_API_KEY: ${{ secrets.BUTLER_CREDENTIALS }}
      run: |
        # 1. On télécharge Butler depuis GitHub (plus fiable que le serveur OVH)
        curl -L -o butler.zip https://github.com/itchio/butler/releases/download/v15.21.0/butler-linux-amd64.zip
        unzip butler.zip
        chmod +x butler

        # 2. Petite vérification (Debug)
        ./butler -V
        
        if [ -z "$BUTLER_API_KEY" ]; then
          echo "❌ ERREUR : La clé API n'est toujours pas vue."
          exit 1
        fi

        # 3. Envoi du jeu
        echo "🚀 Envoi en cours..."
        ./butler push . vandanael/point-the-map:web --userversion-file VERSION || ./butler push . vandanael/point-the-map:web
